apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dapreg-backend-vservice
spec:
  hosts:
    - "{{ .Values.dns }}"
  gateways:
    - istio-system/primary-gateway
  http:
    - name: dapreg-frontend-route
      match:
      - uri:
          prefix: "/admin"
      route:
      - destination:
          host: dapreg-frontend-service
          port:
            number: {{ .Values.service.port }}
    - name: dapreg-backend-route
      route:
        - destination:
            host: dapreg-backend-service
            port:
              number: {{ .Values.service.port }}
