apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dapreg-backend-vservice
spec:
  hosts:
    - "{{ .Values.dns }}"
  gateways:
    - istio-system/primary-gateway
  http:
    - name: dapreg-backend-route
      route:
        - destination:
            host: dapreg-backend-service
            port:
              number: {{ .Values.service.port }}
