apiVersion: v1
kind: Service
metadata:
  name: dapreg-backend-service
spec:
  type: ClusterIP
  selector:
    app: dapreg-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dapreg-frontend-service
spec:
  type: ClusterIP
  selector:
    app: dapreg-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
